[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[build]
  command = "npm run build"
  publish = "build/client"

[dev]
  command = "npm run dev"

[functions]
  directory = "netlify/functions"