[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Build öncesi Firebase yapılandırma dosyası kontrolü
# (Bu kısım GitHub Actions tarafından yönetilecek, ancak Netlify üzerinden deploy durumunda yedek olarak)
[build.lifecycle]
  onPreBuild = 'if [ ! -f "./app/services/firebaseConfig.ts" ]; then echo "Firebase config missing, copying example..."; mkdir -p ./app/services; cp -f ./app/services/firebaseConfig.example.ts ./app/services/firebaseConfig.ts; sed -i "s/YOUR_API_KEY/${FIREBASE_API_KEY}/g" ./app/services/firebaseConfig.ts; sed -i "s/YOUR_AUTH_DOMAIN/${FIREBASE_AUTH_DOMAIN}/g" ./app/services/firebaseConfig.ts; sed -i "s/YOUR_DATABASE_URL/${FIREBASE_DATABASE_URL}/g" ./app/services/firebaseConfig.ts; sed -i "s/YOUR_PROJECT_ID/${FIREBASE_PROJECT_ID}/g" ./app/services/firebaseConfig.ts; sed -i "s/YOUR_STORAGE_BUCKET/${FIREBASE_STORAGE_BUCKET}/g" ./app/services/firebaseConfig.ts; sed -i "s/YOUR_MESSAGING_SENDER_ID/${FIREBASE_MESSAGING_SENDER_ID}/g" ./app/services/firebaseConfig.ts; sed -i "s/YOUR_APP_ID/${FIREBASE_APP_ID}/g" ./app/services/firebaseConfig.ts; sed -i "s/YOUR_MEASUREMENT_ID/${FIREBASE_MEASUREMENT_ID}/g" ./app/services/firebaseConfig.ts; fi'

[dev]
  command = "npm run dev"