[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20"
  # Güvenlik taramasını ayarlıyoruz
  SECRETS_SCAN_ENABLED = "false"
  # Alternatif olarak, belirli dosyaları tarama dışı bırakabiliriz
  SECRETS_SCAN_OMIT_PATHS = ".firebaserc"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Firebase SSR için webpack yapılandırması
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase", "firebase-admin", "firebase/app", "firebase/database"]

# Build öncesi Firebase yapılandırma dosyasını oluştur (GitHub Actions'takine benzer şekilde)
[build.lifecycle]
  onPreBuild = '''
  echo "Firebase yapılandırma dosyası oluşturuluyor..."
  mkdir -p app/services
  cat > app/services/firebaseConfig.ts << EOL
  // Firebase yapılandırma dosyası
  import { initializeApp } from 'firebase/app';
  import { getDatabase } from 'firebase/database';
  import { getAnalytics } from 'firebase/analytics';

  // Firebase yapılandırma detayları
  const firebaseConfig = {
    apiKey: "${FIREBASE_API_KEY}",
    authDomain: "${FIREBASE_AUTH_DOMAIN}",
    databaseURL: "${FIREBASE_DATABASE_URL}",
    projectId: "${FIREBASE_PROJECT_ID}",
    storageBucket: "${FIREBASE_STORAGE_BUCKET}",
    messagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID}",
    appId: "${FIREBASE_APP_ID}",
    measurementId: "${FIREBASE_MEASUREMENT_ID}"
  };

  // Firebase uygulamasını başlat
  const app = initializeApp(firebaseConfig);

  // Realtime Database referansını al
  export const db = getDatabase(app);

  // Analytics'i sadece tarayıcı ortamında başlat
  let analytics = null;
  if (typeof window !== 'undefined') {
    analytics = getAnalytics(app);
  }

  // Firebase bağlantısı için yardımcı fonksiyonlar
  export function getFirebaseDatabase() {
    return db;
  }

  // Bu dosyayı import eden Netlify Functions veya diğer servisler için
  export default {
    app,
    db,
    analytics,
    getFirebaseDatabase,
  };
  EOL
  echo "Firebase yapılandırma dosyası oluşturuldu."
  '''

[dev]
  command = "npm run dev"