name: Deploy to Netlify

on:
  push:
    branches:
      - master # or your default branch

permissions:
  contents: write
  deployments: write
  statuses: write
  pull-requests: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Netlify uses Node 18

      - name: Install dependencies
        run: npm install

      # Firebase yapılandırma dosyasını oluştur
      - name: Create Firebase Configuration
        run: |
          mkdir -p app/services
          cat > app/services/firebaseConfig.ts << 'EOL'
          // Firebase yapılandırma dosyası
          import { initializeApp } from 'firebase/app';
          import { getDatabase } from 'firebase/database';
          import { getAnalytics } from 'firebase/analytics';

          // Firebase yapılandırma detayları
          const firebaseConfig = {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            databaseURL: "${{ secrets.FIREBASE_DATABASE_URL }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}",
            measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
          };

          // Firebase uygulamasını başlat
          const app = initializeApp(firebaseConfig);

          // Realtime Database referansını al
          export const db = getDatabase(app);

          // Analytics'i sadece tarayıcı ortamında başlat
          let analytics = null;
          if (typeof window !== 'undefined') {
            analytics = getAnalytics(app);
          }

          // Firebase bağlantısı için yardımcı fonksiyonlar
          export function getFirebaseDatabase() {
            return db;
          }

          // Bu dosyayı import eden Netlify Functions veya diğer servisler için
          export default {
            app,
            db,
            analytics,
            getFirebaseDatabase,
          };
          EOL
          echo "Firebase configuration file created"

      - name: Build project
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./build/client
          production-branch: master
          deploy-message: "Deployed via GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          # Firebase değişkenlerini de Netlify'a aktar
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
