name: Deploy to Netlify

on:
  push:
    branches:
      - master # or your default branch

permissions:
  contents: write
  deployments: write
  statuses: write
  pull-requests: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23' # change if needed

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # or whatever your build command is

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./build/client # or your output folder (e.g., build, out, etc.)
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deployed via GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
